name: A Tree With Roots Music
favicon: null
layout_spectrum: 0.59859
typography_spectrum: 0.9307188864331692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8726480449549854
  lightness: 0.8630790445022285
  saturation: 0.3493946648668498
  rhythmicContrast: 0.5677433630917221
purpose: []
