name: A Tree With Roots Music
favicon: null
layout_spectrum: 0.59859
typography_spectrum: 0.9307188864331692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#a29f9f'
    - '#6e6e6e'
    - '#c7c7c7'
  brandStrength: 0.8125
  lightness: 0.8630790445022285
  saturation: 0.3493946648668498
  rhythmicContrast: 0.5677433630917221
purpose: []
